### ISSUE TITLE
Is there any way to not deal with content in the pseudo-element?

### ISSUE THREAD

**Issue by airen** [springuper/postcss-viewport-units#2]
@springuper , sometimes, I use pseudo-element to make ICONS. In the pseudo-element has use viewport units, the postcss-viewport-units will replace the content of pseudo-element. eg:

```css
.icon-book::before {
      content: 'book';
      width: 2vw;
      height: 2vw;
}
```

Output CSS:

```CSS
.icon-book::before {
   content: 'viewport-units-buggyfill; width: 2vw;height: 2vw;`
}
```
